### ISSUE TITLE
missing thumbnail list

### ISSUE THREAD

**Issue by markwkidd** [markwkidd/mame2003-plus-thumbnails#1]
**thumbnails need to be in their original/native size. they should be in PNG format**

Named_Snaps=Aqua Rush (AQ1-VER.A).png  (aquarush)
Named_Titles=Aqua Rush (AQ1-VER.A).png  (aquarush)

Named_Snaps=Avengers in Galactic Storm (US).png  (avengrgs)
Named_Titles=Avengers in Galactic Storm (US).png  (avengrgs)

Named_Snaps=Avengers in Galactic Storm (Japan).png  (avengrgsj)
Named_Titles=Avengers in Galactic Storm (Japan).png  (avengrgsj)

Named_Snaps=Bubble Bobble (Ultra Version)(USA).png  (bublboblu)

Named_Snaps=Centipede (bootleg, set 1).png  (centipb2)
Named_Titles=Centipede (bootleg, set 1).png  (centipb2)

Named_Snaps=Donkey Kong - Pauline Edition.png  (dkongpe)
Named_Titles=Donkey Kong - Pauline Edition.png  (dkongpe)

Named_Snaps=Golden Axe (Version 2).png  (goldnaxa)
Named_Titles=Golden Axe (Version 2).png  (goldnaxa)

Named_Snaps=Magic Worm (bootleg of Centipede).png  (magworm)
Named_Titles=Magic Worm (bootleg of Centipede).png  (magworm)

Named_Snaps=SegaSonic Bros (Japan, prototype).png  (ssonicbr)
Named_Titles=SegaSonic Bros (Japan, prototype).png  (ssonicbr)

**Comment by grant2258** [comment]
https://github.com/grant2258/mame2003-plus-libretro/tree/pics/pics

ichidntb  is just a black screen. I dont have bubble bobble ultra so cant help with that one

**Comment by markwkidd** [comment]
Thank you @grant2258 for pitching in. Also, thanks for indirectly tipping me off about the GPU screenshot setting -- once I turned Bilinear Filtering and turned of the GPU screenshots I was able to finish making the last couple of thumbs! :)
